drop table if exists ITEMS;
drop table if exists ORDERS;

CREATE TABLE `ORDERS`(  
        `ORDER_ID`            INT NOT NULL AUTO_INCREMENT,  
        `CUSTOMER_NAME`       VARCHAR(30) NOT NULL,  
        PRIMARY KEY(`ORDER_ID`)  
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8; 

CREATE TABLE `ITEMS`(  
        `ITEM_ID`             INT NOT NULL AUTO_INCREMENT,  
        `PRODUCT_NAME`        VARCHAR(30) NOT NULL,  
        `PRICE`               DECIMAL(10,2) NULL,  
        `QUANTITY`            INT NULL,  
	ORDER_ID 	      INT REFERENCES ORDERS(ORDER_ID),
        PRIMARY KEY(`ITEM_ID`)  
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8; 



SELECT * FROM ORDERS LEFT JOIN ITEMS ON (ORDERS.ORDER_ID = ITEMS.ORDER_ID);